---
- name: configurar servidor de banco de dados
  hosts: db01

  user: vagrant
  become: yes
  vars_files:
    - vars/main.yml
  vars:
    - dbname: "db01"
    - dbusrname: "root"
    - dbpassword: "devopsmaonamassa"
  tasks:
    - name: Configurar hots lan ansible
      lineinfile:
        dest: /etc/hosts
        state: present
        line: "{{item}}"
      with_items:
      - 192.168.1.2 control-node
      - 192.168.1.3 app01
      - 192.168.1.4 db01
  roles:
    - configuracao-default-so
    - role: geerlingguy.mysql




